// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://psoxylumysgpfdqptnyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzb3h5bHVteXNncGZkcXB0bnlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg3MTc2OTQsImV4cCI6MjA5NDI5MzY5NH0.I5y7p3WeoLqq2oZWk9a4XnlE6Eh_jUzZ3ikfVnSFXqI";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);